### ISSUE TITLE
contractor error

### ISSUE THREAD

**Issue by ufodia** [secp256k2/secp256k2#3]
when i tried to run the examples for ex: 
from secp256k2 import Contactor

cont = Contactor()

privatekey = 12345678901234567891234567891234567789

ripemd160 = cont.privatekey_to_h160(privatekey)

i get this error: 
    ripemd160 = cont.privatekey_to_h160(privatekey)
                ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Contactor' object has no attribute 'privatekey_to_h160'

i get similar errors from the other examples.

**Comment by Pymmdrza** [comment]
> when i tried to run the examples for ex: from secp256k2 import Contactor
> 
> cont = Contactor()
> 
> privatekey = 12345678901234567891234567891234567789
> 
> ripemd160 = cont.privatekey_to_h160(privatekey)
> 
> i get this error: ripemd160 = cont.privatekey_to_h160(privatekey) ^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'Contactor' object has no attribute 'privatekey_to_h160'
> 
> i get similar errors from the other examples.

`pip install --upgrade secp256k2`

or

```
pip uninstall secp256k2
# answer : y
pip install secp256k2
```
linux : 

```
sudo apt-get update&&sudo apt-get upgrade -y
sudo apt-get install python3-pip
pip3 install secp256k2
```
or

`pip3 install --upgrade secp256k2`

```
pip3 uninstall secp256k2
# answer : y
pip3 install secp256k2
``

**Comment by Pymmdrza** [comment]
> when i tried to run the examples for ex: from secp256k2 import Contactor
> 
> cont = Contactor()
> 
> privatekey = 12345678901234567891234567891234567789
> 
> ripemd160 = cont.privatekey_to_h160(privatekey)
> 
> i get this error: ripemd160 = cont.privatekey_to_h160(privatekey) ^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'Contactor' object has no attribute 'privatekey_to_h160'
> 
> i get similar errors from the other examples.

```cmd
pip uninstall -y secp256k2
pip install --upgrade secp256k2
```
